spring.application.name=moovieMatcher

# datasource PostgreSGL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/MoovieMatcher
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.database=postgresql
spring.jpa.show-sql=true

# generate schema ddl to create tables (update nog weer aanpassen naar create)
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with data.sql after hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# secret key
jwt.secret=${JWT_SECRET}
